package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallStockInfo;
import org.linlinjava.litemall.db.domain.LitemallStockInfoExample;

public interface LitemallStockInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    long countByExample(LitemallStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int insert(LitemallStockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int insertSelective(LitemallStockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    LitemallStockInfo selectOneByExample(LitemallStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    LitemallStockInfo selectOneByExampleSelective(@Param("example") LitemallStockInfoExample example, @Param("selective") LitemallStockInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    List<LitemallStockInfo> selectByExampleSelective(@Param("example") LitemallStockInfoExample example, @Param("selective") LitemallStockInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    List<LitemallStockInfo> selectByExample(LitemallStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    LitemallStockInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallStockInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    LitemallStockInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    LitemallStockInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallStockInfo record, @Param("example") LitemallStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallStockInfo record, @Param("example") LitemallStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallStockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallStockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallStockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_info
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}