package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallXmfeedback;
import org.linlinjava.litemall.db.domain.LitemallXmfeedbackExample;

public interface LitemallXmfeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    long countByExample(LitemallXmfeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallXmfeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int insert(LitemallXmfeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int insertSelective(LitemallXmfeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    LitemallXmfeedback selectOneByExample(LitemallXmfeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    LitemallXmfeedback selectOneByExampleSelective(@Param("example") LitemallXmfeedbackExample example, @Param("selective") LitemallXmfeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    List<LitemallXmfeedback> selectByExampleSelective(@Param("example") LitemallXmfeedbackExample example, @Param("selective") LitemallXmfeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    List<LitemallXmfeedback> selectByExample(LitemallXmfeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    LitemallXmfeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallXmfeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    LitemallXmfeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    LitemallXmfeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallXmfeedback record, @Param("example") LitemallXmfeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallXmfeedback record, @Param("example") LitemallXmfeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallXmfeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallXmfeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallXmfeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_xmfeedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}