package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallFileDetail;
import org.linlinjava.litemall.db.domain.LitemallFileDetailExample;

public interface LitemallFileDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    long countByExample(LitemallFileDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallFileDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int insert(LitemallFileDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int insertSelective(LitemallFileDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    LitemallFileDetail selectOneByExample(LitemallFileDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    LitemallFileDetail selectOneByExampleSelective(@Param("example") LitemallFileDetailExample example, @Param("selective") LitemallFileDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    List<LitemallFileDetail> selectByExampleSelective(@Param("example") LitemallFileDetailExample example, @Param("selective") LitemallFileDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    List<LitemallFileDetail> selectByExample(LitemallFileDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    LitemallFileDetail selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallFileDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    LitemallFileDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallFileDetail record, @Param("example") LitemallFileDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallFileDetail record, @Param("example") LitemallFileDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallFileDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_file_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallFileDetail record);
}