package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQuoteModel;
import org.linlinjava.litemall.db.domain.LitemallQuoteModelExample;

public interface LitemallQuoteModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    long countByExample(LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int insert(LitemallQuoteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQuoteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    LitemallQuoteModel selectOneByExample(LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    LitemallQuoteModel selectOneByExampleSelective(@Param("example") LitemallQuoteModelExample example, @Param("selective") LitemallQuoteModel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    LitemallQuoteModel selectOneByExampleWithBLOBs(LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    List<LitemallQuoteModel> selectByExampleSelective(@Param("example") LitemallQuoteModelExample example, @Param("selective") LitemallQuoteModel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    List<LitemallQuoteModel> selectByExampleWithBLOBs(LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    List<LitemallQuoteModel> selectByExample(LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    LitemallQuoteModel selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallQuoteModel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    LitemallQuoteModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    LitemallQuoteModel selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQuoteModel record, @Param("example") LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallQuoteModel record, @Param("example") LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQuoteModel record, @Param("example") LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQuoteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallQuoteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQuoteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallQuoteModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_model
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}