package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQuoteElectronic;
import org.linlinjava.litemall.db.domain.LitemallQuoteElectronicExample;

public interface LitemallQuoteElectronicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    long countByExample(LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int insert(LitemallQuoteElectronic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQuoteElectronic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    LitemallQuoteElectronic selectOneByExample(LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    LitemallQuoteElectronic selectOneByExampleSelective(@Param("example") LitemallQuoteElectronicExample example, @Param("selective") LitemallQuoteElectronic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    LitemallQuoteElectronic selectOneByExampleWithBLOBs(LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    List<LitemallQuoteElectronic> selectByExampleSelective(@Param("example") LitemallQuoteElectronicExample example, @Param("selective") LitemallQuoteElectronic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    List<LitemallQuoteElectronic> selectByExampleWithBLOBs(LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    List<LitemallQuoteElectronic> selectByExample(LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    LitemallQuoteElectronic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallQuoteElectronic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    LitemallQuoteElectronic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    LitemallQuoteElectronic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQuoteElectronic record, @Param("example") LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallQuoteElectronic record, @Param("example") LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQuoteElectronic record, @Param("example") LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQuoteElectronic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallQuoteElectronic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQuoteElectronic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallQuoteElectronicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}