package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQuoteHardware;
import org.linlinjava.litemall.db.domain.LitemallQuoteHardwareExample;

public interface LitemallQuoteHardwareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    long countByExample(LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int insert(LitemallQuoteHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQuoteHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    LitemallQuoteHardware selectOneByExample(LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    LitemallQuoteHardware selectOneByExampleSelective(@Param("example") LitemallQuoteHardwareExample example, @Param("selective") LitemallQuoteHardware.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    LitemallQuoteHardware selectOneByExampleWithBLOBs(LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    List<LitemallQuoteHardware> selectByExampleSelective(@Param("example") LitemallQuoteHardwareExample example, @Param("selective") LitemallQuoteHardware.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    List<LitemallQuoteHardware> selectByExampleWithBLOBs(LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    List<LitemallQuoteHardware> selectByExample(LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    LitemallQuoteHardware selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallQuoteHardware.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    LitemallQuoteHardware selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    LitemallQuoteHardware selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQuoteHardware record, @Param("example") LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallQuoteHardware record, @Param("example") LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQuoteHardware record, @Param("example") LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQuoteHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallQuoteHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQuoteHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallQuoteHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_hardware
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}