package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSupplyInfo;
import org.linlinjava.litemall.db.domain.LitemallSupplyInfoExample;

public interface LitemallSupplyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    long countByExample(LitemallSupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int insert(LitemallSupplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSupplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    LitemallSupplyInfo selectOneByExample(LitemallSupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    LitemallSupplyInfo selectOneByExampleSelective(@Param("example") LitemallSupplyInfoExample example, @Param("selective") LitemallSupplyInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    List<LitemallSupplyInfo> selectByExampleSelective(@Param("example") LitemallSupplyInfoExample example, @Param("selective") LitemallSupplyInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    List<LitemallSupplyInfo> selectByExample(LitemallSupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    LitemallSupplyInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSupplyInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    LitemallSupplyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    LitemallSupplyInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSupplyInfo record, @Param("example") LitemallSupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSupplyInfo record, @Param("example") LitemallSupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSupplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSupplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supply_info
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}