package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPackingTactics;
import org.linlinjava.litemall.db.domain.LitemallPackingTacticsExample;

public interface LitemallPackingTacticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    long countByExample(LitemallPackingTacticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPackingTacticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int insert(LitemallPackingTactics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPackingTactics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    LitemallPackingTactics selectOneByExample(LitemallPackingTacticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    LitemallPackingTactics selectOneByExampleSelective(@Param("example") LitemallPackingTacticsExample example, @Param("selective") LitemallPackingTactics.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    List<LitemallPackingTactics> selectByExampleSelective(@Param("example") LitemallPackingTacticsExample example, @Param("selective") LitemallPackingTactics.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    List<LitemallPackingTactics> selectByExample(LitemallPackingTacticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    LitemallPackingTactics selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPackingTactics.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    LitemallPackingTactics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    LitemallPackingTactics selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPackingTactics record, @Param("example") LitemallPackingTacticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPackingTactics record, @Param("example") LitemallPackingTacticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPackingTactics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPackingTactics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPackingTacticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}