package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallKnowledge;
import org.linlinjava.litemall.db.domain.LitemallKnowledgeExample;

public interface LitemallKnowledgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    long countByExample(LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int insert(LitemallKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int insertSelective(LitemallKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    LitemallKnowledge selectOneByExample(LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    LitemallKnowledge selectOneByExampleSelective(@Param("example") LitemallKnowledgeExample example, @Param("selective") LitemallKnowledge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    LitemallKnowledge selectOneByExampleWithBLOBs(LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    List<LitemallKnowledge> selectByExampleSelective(@Param("example") LitemallKnowledgeExample example, @Param("selective") LitemallKnowledge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    List<LitemallKnowledge> selectByExampleWithBLOBs(LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    List<LitemallKnowledge> selectByExample(LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    LitemallKnowledge selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallKnowledge.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    LitemallKnowledge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    LitemallKnowledge selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallKnowledge record, @Param("example") LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallKnowledge record, @Param("example") LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallKnowledge record, @Param("example") LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_knowledge
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}