package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPacking;
import org.linlinjava.litemall.db.domain.LitemallPackingExample;

public interface LitemallPackingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    long countByExample(LitemallPackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int insert(LitemallPacking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPacking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    LitemallPacking selectOneByExample(LitemallPackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    LitemallPacking selectOneByExampleSelective(@Param("example") LitemallPackingExample example, @Param("selective") LitemallPacking.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    List<LitemallPacking> selectByExampleSelective(@Param("example") LitemallPackingExample example, @Param("selective") LitemallPacking.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    List<LitemallPacking> selectByExample(LitemallPackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    LitemallPacking selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPacking.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    LitemallPacking selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    LitemallPacking selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPacking record, @Param("example") LitemallPackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPacking record, @Param("example") LitemallPackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPacking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPacking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}