package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQuoteBill;
import org.linlinjava.litemall.db.domain.LitemallQuoteBillExample;
import org.linlinjava.litemall.db.domain.LitemallRequote;
import org.linlinjava.litemall.db.domain.LitemallRequoteExample;

public interface LitemallQuoteBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    long countByExample(LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int insert(LitemallQuoteBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQuoteBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    LitemallQuoteBill selectOneByExample(LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    LitemallQuoteBill selectOneByExampleSelective(@Param("example") LitemallQuoteBillExample example, @Param("selective") LitemallQuoteBill.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    List<LitemallQuoteBill> selectByExampleSelective(@Param("example") LitemallQuoteBillExample example, @Param("selective") LitemallQuoteBill.Column ... selective);

    LitemallQuoteBill selectOneByExampleWithBLOBs(LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    List<LitemallQuoteBill> selectByExample(LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    LitemallQuoteBill selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallQuoteBill.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    LitemallQuoteBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    LitemallQuoteBill selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQuoteBill record, @Param("example") LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQuoteBill record, @Param("example") LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQuoteBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQuoteBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallQuoteBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_bill
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}