package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPackingSelect;
import org.linlinjava.litemall.db.domain.LitemallPackingSelectExample;

public interface LitemallPackingSelectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    long countByExample(LitemallPackingSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPackingSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int insert(LitemallPackingSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPackingSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    LitemallPackingSelect selectOneByExample(LitemallPackingSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    LitemallPackingSelect selectOneByExampleSelective(@Param("example") LitemallPackingSelectExample example, @Param("selective") LitemallPackingSelect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    List<LitemallPackingSelect> selectByExampleSelective(@Param("example") LitemallPackingSelectExample example, @Param("selective") LitemallPackingSelect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    List<LitemallPackingSelect> selectByExample(LitemallPackingSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    LitemallPackingSelect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPackingSelect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    LitemallPackingSelect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    LitemallPackingSelect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPackingSelect record, @Param("example") LitemallPackingSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPackingSelect record, @Param("example") LitemallPackingSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPackingSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPackingSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPackingSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_select
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}