package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallQuoteElectronic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.quote_id
     *
     * @mbg.generated
     */
    private Integer quoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.quantity_year
     *
     * @mbg.generated
     */
    private String quantityYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.delivery
     *
     * @mbg.generated
     */
    private String delivery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.moq
     *
     * @mbg.generated
     */
    private String moq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.mpq
     *
     * @mbg.generated
     */
    private String mpq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.package_size
     *
     * @mbg.generated
     */
    private String packageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.certificate
     *
     * @mbg.generated
     */
    private String certificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.bill_id
     *
     * @mbg.generated
     */
    private Boolean billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.is_duty
     *
     * @mbg.generated
     */
    private Boolean isDuty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.is_ceo
     *
     * @mbg.generated
     */
    private Boolean isCeo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.is_recheck
     *
     * @mbg.generated
     */
    private Boolean isRecheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_quote_electronic.appendix
     *
     * @mbg.generated
     */
    private String appendix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.id
     *
     * @return the value of litemall_quote_electronic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.id
     *
     * @param id the value for litemall_quote_electronic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.quote_id
     *
     * @return the value of litemall_quote_electronic.quote_id
     *
     * @mbg.generated
     */
    public Integer getQuoteId() {
        return quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.quote_id
     *
     * @param quoteId the value for litemall_quote_electronic.quote_id
     *
     * @mbg.generated
     */
    public void setQuoteId(Integer quoteId) {
        this.quoteId = quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.code
     *
     * @return the value of litemall_quote_electronic.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.code
     *
     * @param code the value for litemall_quote_electronic.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.name
     *
     * @return the value of litemall_quote_electronic.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.name
     *
     * @param name the value for litemall_quote_electronic.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.spec
     *
     * @return the value of litemall_quote_electronic.spec
     *
     * @mbg.generated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.spec
     *
     * @param spec the value for litemall_quote_electronic.spec
     *
     * @mbg.generated
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.quantity_year
     *
     * @return the value of litemall_quote_electronic.quantity_year
     *
     * @mbg.generated
     */
    public String getQuantityYear() {
        return quantityYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.quantity_year
     *
     * @param quantityYear the value for litemall_quote_electronic.quantity_year
     *
     * @mbg.generated
     */
    public void setQuantityYear(String quantityYear) {
        this.quantityYear = quantityYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.price
     *
     * @return the value of litemall_quote_electronic.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.price
     *
     * @param price the value for litemall_quote_electronic.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.delivery
     *
     * @return the value of litemall_quote_electronic.delivery
     *
     * @mbg.generated
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.delivery
     *
     * @param delivery the value for litemall_quote_electronic.delivery
     *
     * @mbg.generated
     */
    public void setDelivery(String delivery) {
        this.delivery = delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.moq
     *
     * @return the value of litemall_quote_electronic.moq
     *
     * @mbg.generated
     */
    public String getMoq() {
        return moq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.moq
     *
     * @param moq the value for litemall_quote_electronic.moq
     *
     * @mbg.generated
     */
    public void setMoq(String moq) {
        this.moq = moq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.mpq
     *
     * @return the value of litemall_quote_electronic.mpq
     *
     * @mbg.generated
     */
    public String getMpq() {
        return mpq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.mpq
     *
     * @param mpq the value for litemall_quote_electronic.mpq
     *
     * @mbg.generated
     */
    public void setMpq(String mpq) {
        this.mpq = mpq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.package_size
     *
     * @return the value of litemall_quote_electronic.package_size
     *
     * @mbg.generated
     */
    public String getPackageSize() {
        return packageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.package_size
     *
     * @param packageSize the value for litemall_quote_electronic.package_size
     *
     * @mbg.generated
     */
    public void setPackageSize(String packageSize) {
        this.packageSize = packageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.brand
     *
     * @return the value of litemall_quote_electronic.brand
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.brand
     *
     * @param brand the value for litemall_quote_electronic.brand
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.certificate
     *
     * @return the value of litemall_quote_electronic.certificate
     *
     * @mbg.generated
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.certificate
     *
     * @param certificate the value for litemall_quote_electronic.certificate
     *
     * @mbg.generated
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.status
     *
     * @return the value of litemall_quote_electronic.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.status
     *
     * @param status the value for litemall_quote_electronic.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.note
     *
     * @return the value of litemall_quote_electronic.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.note
     *
     * @param note the value for litemall_quote_electronic.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.add_time
     *
     * @return the value of litemall_quote_electronic.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.add_time
     *
     * @param addTime the value for litemall_quote_electronic.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.update_time
     *
     * @return the value of litemall_quote_electronic.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.update_time
     *
     * @param updateTime the value for litemall_quote_electronic.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.deleted
     *
     * @return the value of litemall_quote_electronic.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.deleted
     *
     * @param deleted the value for litemall_quote_electronic.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.bill_id
     *
     * @return the value of litemall_quote_electronic.bill_id
     *
     * @mbg.generated
     */
    public Boolean getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.bill_id
     *
     * @param billId the value for litemall_quote_electronic.bill_id
     *
     * @mbg.generated
     */
    public void setBillId(Boolean billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.is_duty
     *
     * @return the value of litemall_quote_electronic.is_duty
     *
     * @mbg.generated
     */
    public Boolean getIsDuty() {
        return isDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.is_duty
     *
     * @param isDuty the value for litemall_quote_electronic.is_duty
     *
     * @mbg.generated
     */
    public void setIsDuty(Boolean isDuty) {
        this.isDuty = isDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.is_ceo
     *
     * @return the value of litemall_quote_electronic.is_ceo
     *
     * @mbg.generated
     */
    public Boolean getIsCeo() {
        return isCeo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.is_ceo
     *
     * @param isCeo the value for litemall_quote_electronic.is_ceo
     *
     * @mbg.generated
     */
    public void setIsCeo(Boolean isCeo) {
        this.isCeo = isCeo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.is_recheck
     *
     * @return the value of litemall_quote_electronic.is_recheck
     *
     * @mbg.generated
     */
    public Boolean getIsRecheck() {
        return isRecheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.is_recheck
     *
     * @param isRecheck the value for litemall_quote_electronic.is_recheck
     *
     * @mbg.generated
     */
    public void setIsRecheck(Boolean isRecheck) {
        this.isRecheck = isRecheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_quote_electronic.appendix
     *
     * @return the value of litemall_quote_electronic.appendix
     *
     * @mbg.generated
     */
    public String getAppendix() {
        return appendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_quote_electronic.appendix
     *
     * @param appendix the value for litemall_quote_electronic.appendix
     *
     * @mbg.generated
     */
    public void setAppendix(String appendix) {
        this.appendix = appendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", quoteId=").append(quoteId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", spec=").append(spec);
        sb.append(", quantityYear=").append(quantityYear);
        sb.append(", price=").append(price);
        sb.append(", delivery=").append(delivery);
        sb.append(", moq=").append(moq);
        sb.append(", mpq=").append(mpq);
        sb.append(", packageSize=").append(packageSize);
        sb.append(", brand=").append(brand);
        sb.append(", certificate=").append(certificate);
        sb.append(", status=").append(status);
        sb.append(", note=").append(note);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", billId=").append(billId);
        sb.append(", isDuty=").append(isDuty);
        sb.append(", isCeo=").append(isCeo);
        sb.append(", isRecheck=").append(isRecheck);
        sb.append(", appendix=").append(appendix);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallQuoteElectronic other = (LitemallQuoteElectronic) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQuoteId() == null ? other.getQuoteId() == null : this.getQuoteId().equals(other.getQuoteId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSpec() == null ? other.getSpec() == null : this.getSpec().equals(other.getSpec()))
            && (this.getQuantityYear() == null ? other.getQuantityYear() == null : this.getQuantityYear().equals(other.getQuantityYear()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getDelivery() == null ? other.getDelivery() == null : this.getDelivery().equals(other.getDelivery()))
            && (this.getMoq() == null ? other.getMoq() == null : this.getMoq().equals(other.getMoq()))
            && (this.getMpq() == null ? other.getMpq() == null : this.getMpq().equals(other.getMpq()))
            && (this.getPackageSize() == null ? other.getPackageSize() == null : this.getPackageSize().equals(other.getPackageSize()))
            && (this.getBrand() == null ? other.getBrand() == null : this.getBrand().equals(other.getBrand()))
            && (this.getCertificate() == null ? other.getCertificate() == null : this.getCertificate().equals(other.getCertificate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getBillId() == null ? other.getBillId() == null : this.getBillId().equals(other.getBillId()))
            && (this.getIsDuty() == null ? other.getIsDuty() == null : this.getIsDuty().equals(other.getIsDuty()))
            && (this.getIsCeo() == null ? other.getIsCeo() == null : this.getIsCeo().equals(other.getIsCeo()))
            && (this.getIsRecheck() == null ? other.getIsRecheck() == null : this.getIsRecheck().equals(other.getIsRecheck()))
            && (this.getAppendix() == null ? other.getAppendix() == null : this.getAppendix().equals(other.getAppendix()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQuoteId() == null) ? 0 : getQuoteId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSpec() == null) ? 0 : getSpec().hashCode());
        result = prime * result + ((getQuantityYear() == null) ? 0 : getQuantityYear().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getDelivery() == null) ? 0 : getDelivery().hashCode());
        result = prime * result + ((getMoq() == null) ? 0 : getMoq().hashCode());
        result = prime * result + ((getMpq() == null) ? 0 : getMpq().hashCode());
        result = prime * result + ((getPackageSize() == null) ? 0 : getPackageSize().hashCode());
        result = prime * result + ((getBrand() == null) ? 0 : getBrand().hashCode());
        result = prime * result + ((getCertificate() == null) ? 0 : getCertificate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getBillId() == null) ? 0 : getBillId().hashCode());
        result = prime * result + ((getIsDuty() == null) ? 0 : getIsDuty().hashCode());
        result = prime * result + ((getIsCeo() == null) ? 0 : getIsCeo().hashCode());
        result = prime * result + ((getIsRecheck() == null) ? 0 : getIsRecheck().hashCode());
        result = prime * result + ((getAppendix() == null) ? 0 : getAppendix().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_quote_electronic
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        quoteId("quote_id", "quoteId", "INTEGER", false),
        code("code", "code", "VARCHAR", false),
        name("name", "name", "VARCHAR", true),
        spec("spec", "spec", "VARCHAR", false),
        quantityYear("quantity_year", "quantityYear", "VARCHAR", false),
        price("price", "price", "DECIMAL", false),
        delivery("delivery", "delivery", "VARCHAR", false),
        moq("moq", "moq", "VARCHAR", false),
        mpq("mpq", "mpq", "VARCHAR", false),
        packageSize("package_size", "packageSize", "VARCHAR", false),
        brand("brand", "brand", "VARCHAR", false),
        certificate("certificate", "certificate", "VARCHAR", false),
        status("status", "status", "SMALLINT", true),
        note("note", "note", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        billId("bill_id", "billId", "BIT", false),
        isDuty("is_duty", "isDuty", "BIT", false),
        isCeo("is_ceo", "isCeo", "BIT", false),
        isRecheck("is_recheck", "isRecheck", "BIT", false),
        appendix("appendix", "appendix", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_quote_electronic
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}