package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallRequote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.quote_id
     *
     * @mbg.generated
     */
    private Integer quoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.quote_date
     *
     * @mbg.generated
     */
    private LocalDateTime quoteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.requote_excel
     *
     * @mbg.generated
     */
    private String requoteExcel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.quote_model_excel_supply
     *
     * @mbg.generated
     */
    private String quoteModelExcelSupply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.submit_date
     *
     * @mbg.generated
     */
    private LocalDateTime submitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.dead_date
     *
     * @mbg.generated
     */
    private LocalDateTime deadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_requote.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.id
     *
     * @return the value of litemall_requote.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.id
     *
     * @param id the value for litemall_requote.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.quote_id
     *
     * @return the value of litemall_requote.quote_id
     *
     * @mbg.generated
     */
    public Integer getQuoteId() {
        return quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.quote_id
     *
     * @param quoteId the value for litemall_requote.quote_id
     *
     * @mbg.generated
     */
    public void setQuoteId(Integer quoteId) {
        this.quoteId = quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.admin_id
     *
     * @return the value of litemall_requote.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.admin_id
     *
     * @param adminId the value for litemall_requote.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.admin_name
     *
     * @return the value of litemall_requote.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.admin_name
     *
     * @param adminName the value for litemall_requote.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.quote_date
     *
     * @return the value of litemall_requote.quote_date
     *
     * @mbg.generated
     */
    public LocalDateTime getQuoteDate() {
        return quoteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.quote_date
     *
     * @param quoteDate the value for litemall_requote.quote_date
     *
     * @mbg.generated
     */
    public void setQuoteDate(LocalDateTime quoteDate) {
        this.quoteDate = quoteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.note
     *
     * @return the value of litemall_requote.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.note
     *
     * @param note the value for litemall_requote.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.requote_excel
     *
     * @return the value of litemall_requote.requote_excel
     *
     * @mbg.generated
     */
    public String getRequoteExcel() {
        return requoteExcel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.requote_excel
     *
     * @param requoteExcel the value for litemall_requote.requote_excel
     *
     * @mbg.generated
     */
    public void setRequoteExcel(String requoteExcel) {
        this.requoteExcel = requoteExcel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.status
     *
     * @return the value of litemall_requote.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.status
     *
     * @param status the value for litemall_requote.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.quote_model_excel_supply
     *
     * @return the value of litemall_requote.quote_model_excel_supply
     *
     * @mbg.generated
     */
    public String getQuoteModelExcelSupply() {
        return quoteModelExcelSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.quote_model_excel_supply
     *
     * @param quoteModelExcelSupply the value for litemall_requote.quote_model_excel_supply
     *
     * @mbg.generated
     */
    public void setQuoteModelExcelSupply(String quoteModelExcelSupply) {
        this.quoteModelExcelSupply = quoteModelExcelSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.submit_date
     *
     * @return the value of litemall_requote.submit_date
     *
     * @mbg.generated
     */
    public LocalDateTime getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.submit_date
     *
     * @param submitDate the value for litemall_requote.submit_date
     *
     * @mbg.generated
     */
    public void setSubmitDate(LocalDateTime submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.dead_date
     *
     * @return the value of litemall_requote.dead_date
     *
     * @mbg.generated
     */
    public LocalDateTime getDeadDate() {
        return deadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.dead_date
     *
     * @param deadDate the value for litemall_requote.dead_date
     *
     * @mbg.generated
     */
    public void setDeadDate(LocalDateTime deadDate) {
        this.deadDate = deadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.add_time
     *
     * @return the value of litemall_requote.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.add_time
     *
     * @param addTime the value for litemall_requote.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.update_time
     *
     * @return the value of litemall_requote.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.update_time
     *
     * @param updateTime the value for litemall_requote.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_requote.deleted
     *
     * @return the value of litemall_requote.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_requote.deleted
     *
     * @param deleted the value for litemall_requote.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", quoteId=").append(quoteId);
        sb.append(", adminId=").append(adminId);
        sb.append(", adminName=").append(adminName);
        sb.append(", quoteDate=").append(quoteDate);
        sb.append(", note=").append(note);
        sb.append(", requoteExcel=").append(requoteExcel);
        sb.append(", status=").append(status);
        sb.append(", quoteModelExcelSupply=").append(quoteModelExcelSupply);
        sb.append(", submitDate=").append(submitDate);
        sb.append(", deadDate=").append(deadDate);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallRequote other = (LitemallRequote) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQuoteId() == null ? other.getQuoteId() == null : this.getQuoteId().equals(other.getQuoteId()))
            && (this.getAdminId() == null ? other.getAdminId() == null : this.getAdminId().equals(other.getAdminId()))
            && (this.getAdminName() == null ? other.getAdminName() == null : this.getAdminName().equals(other.getAdminName()))
            && (this.getQuoteDate() == null ? other.getQuoteDate() == null : this.getQuoteDate().equals(other.getQuoteDate()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getRequoteExcel() == null ? other.getRequoteExcel() == null : this.getRequoteExcel().equals(other.getRequoteExcel()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getQuoteModelExcelSupply() == null ? other.getQuoteModelExcelSupply() == null : this.getQuoteModelExcelSupply().equals(other.getQuoteModelExcelSupply()))
            && (this.getSubmitDate() == null ? other.getSubmitDate() == null : this.getSubmitDate().equals(other.getSubmitDate()))
            && (this.getDeadDate() == null ? other.getDeadDate() == null : this.getDeadDate().equals(other.getDeadDate()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQuoteId() == null) ? 0 : getQuoteId().hashCode());
        result = prime * result + ((getAdminId() == null) ? 0 : getAdminId().hashCode());
        result = prime * result + ((getAdminName() == null) ? 0 : getAdminName().hashCode());
        result = prime * result + ((getQuoteDate() == null) ? 0 : getQuoteDate().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getRequoteExcel() == null) ? 0 : getRequoteExcel().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getQuoteModelExcelSupply() == null) ? 0 : getQuoteModelExcelSupply().hashCode());
        result = prime * result + ((getSubmitDate() == null) ? 0 : getSubmitDate().hashCode());
        result = prime * result + ((getDeadDate() == null) ? 0 : getDeadDate().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_requote
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        quoteId("quote_id", "quoteId", "INTEGER", false),
        adminId("admin_id", "adminId", "INTEGER", false),
        adminName("admin_name", "adminName", "VARCHAR", false),
        quoteDate("quote_date", "quoteDate", "TIMESTAMP", false),
        note("note", "note", "VARCHAR", false),
        requoteExcel("requote_excel", "requoteExcel", "VARCHAR", false),
        status("status", "status", "SMALLINT", true),
        quoteModelExcelSupply("quote_model_excel_supply", "quoteModelExcelSupply", "VARCHAR", false),
        submitDate("submit_date", "submitDate", "TIMESTAMP", false),
        deadDate("dead_date", "deadDate", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_requote
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}