package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallPackingTactics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.file_id
     *
     * @mbg.generated
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.width_priority
     *
     * @mbg.generated
     */
    private Boolean widthPriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.length_priority
     *
     * @mbg.generated
     */
    private Boolean lengthPriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.quantity_priority
     *
     * @mbg.generated
     */
    private Boolean quantityPriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.cube_priority
     *
     * @mbg.generated
     */
    private Boolean cubePriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.depth_search
     *
     * @mbg.generated
     */
    private Boolean depthSearch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.Shallowness_search
     *
     * @mbg.generated
     */
    private Boolean shallownessSearch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.free_space_search
     *
     * @mbg.generated
     */
    private Boolean freeSpaceSearch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_packing_tactics.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.id
     *
     * @return the value of litemall_packing_tactics.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.id
     *
     * @param id the value for litemall_packing_tactics.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.file_id
     *
     * @return the value of litemall_packing_tactics.file_id
     *
     * @mbg.generated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.file_id
     *
     * @param fileId the value for litemall_packing_tactics.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.width_priority
     *
     * @return the value of litemall_packing_tactics.width_priority
     *
     * @mbg.generated
     */
    public Boolean getWidthPriority() {
        return widthPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.width_priority
     *
     * @param widthPriority the value for litemall_packing_tactics.width_priority
     *
     * @mbg.generated
     */
    public void setWidthPriority(Boolean widthPriority) {
        this.widthPriority = widthPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.length_priority
     *
     * @return the value of litemall_packing_tactics.length_priority
     *
     * @mbg.generated
     */
    public Boolean getLengthPriority() {
        return lengthPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.length_priority
     *
     * @param lengthPriority the value for litemall_packing_tactics.length_priority
     *
     * @mbg.generated
     */
    public void setLengthPriority(Boolean lengthPriority) {
        this.lengthPriority = lengthPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.quantity_priority
     *
     * @return the value of litemall_packing_tactics.quantity_priority
     *
     * @mbg.generated
     */
    public Boolean getQuantityPriority() {
        return quantityPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.quantity_priority
     *
     * @param quantityPriority the value for litemall_packing_tactics.quantity_priority
     *
     * @mbg.generated
     */
    public void setQuantityPriority(Boolean quantityPriority) {
        this.quantityPriority = quantityPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.cube_priority
     *
     * @return the value of litemall_packing_tactics.cube_priority
     *
     * @mbg.generated
     */
    public Boolean getCubePriority() {
        return cubePriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.cube_priority
     *
     * @param cubePriority the value for litemall_packing_tactics.cube_priority
     *
     * @mbg.generated
     */
    public void setCubePriority(Boolean cubePriority) {
        this.cubePriority = cubePriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.depth_search
     *
     * @return the value of litemall_packing_tactics.depth_search
     *
     * @mbg.generated
     */
    public Boolean getDepthSearch() {
        return depthSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.depth_search
     *
     * @param depthSearch the value for litemall_packing_tactics.depth_search
     *
     * @mbg.generated
     */
    public void setDepthSearch(Boolean depthSearch) {
        this.depthSearch = depthSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.Shallowness_search
     *
     * @return the value of litemall_packing_tactics.Shallowness_search
     *
     * @mbg.generated
     */
    public Boolean getShallownessSearch() {
        return shallownessSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.Shallowness_search
     *
     * @param shallownessSearch the value for litemall_packing_tactics.Shallowness_search
     *
     * @mbg.generated
     */
    public void setShallownessSearch(Boolean shallownessSearch) {
        this.shallownessSearch = shallownessSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.free_space_search
     *
     * @return the value of litemall_packing_tactics.free_space_search
     *
     * @mbg.generated
     */
    public Boolean getFreeSpaceSearch() {
        return freeSpaceSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.free_space_search
     *
     * @param freeSpaceSearch the value for litemall_packing_tactics.free_space_search
     *
     * @mbg.generated
     */
    public void setFreeSpaceSearch(Boolean freeSpaceSearch) {
        this.freeSpaceSearch = freeSpaceSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.add_time
     *
     * @return the value of litemall_packing_tactics.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.add_time
     *
     * @param addTime the value for litemall_packing_tactics.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.update_time
     *
     * @return the value of litemall_packing_tactics.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.update_time
     *
     * @param updateTime the value for litemall_packing_tactics.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_packing_tactics.deleted
     *
     * @return the value of litemall_packing_tactics.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_packing_tactics.deleted
     *
     * @param deleted the value for litemall_packing_tactics.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", fileId=").append(fileId);
        sb.append(", widthPriority=").append(widthPriority);
        sb.append(", lengthPriority=").append(lengthPriority);
        sb.append(", quantityPriority=").append(quantityPriority);
        sb.append(", cubePriority=").append(cubePriority);
        sb.append(", depthSearch=").append(depthSearch);
        sb.append(", shallownessSearch=").append(shallownessSearch);
        sb.append(", freeSpaceSearch=").append(freeSpaceSearch);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallPackingTactics other = (LitemallPackingTactics) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getWidthPriority() == null ? other.getWidthPriority() == null : this.getWidthPriority().equals(other.getWidthPriority()))
            && (this.getLengthPriority() == null ? other.getLengthPriority() == null : this.getLengthPriority().equals(other.getLengthPriority()))
            && (this.getQuantityPriority() == null ? other.getQuantityPriority() == null : this.getQuantityPriority().equals(other.getQuantityPriority()))
            && (this.getCubePriority() == null ? other.getCubePriority() == null : this.getCubePriority().equals(other.getCubePriority()))
            && (this.getDepthSearch() == null ? other.getDepthSearch() == null : this.getDepthSearch().equals(other.getDepthSearch()))
            && (this.getShallownessSearch() == null ? other.getShallownessSearch() == null : this.getShallownessSearch().equals(other.getShallownessSearch()))
            && (this.getFreeSpaceSearch() == null ? other.getFreeSpaceSearch() == null : this.getFreeSpaceSearch().equals(other.getFreeSpaceSearch()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getWidthPriority() == null) ? 0 : getWidthPriority().hashCode());
        result = prime * result + ((getLengthPriority() == null) ? 0 : getLengthPriority().hashCode());
        result = prime * result + ((getQuantityPriority() == null) ? 0 : getQuantityPriority().hashCode());
        result = prime * result + ((getCubePriority() == null) ? 0 : getCubePriority().hashCode());
        result = prime * result + ((getDepthSearch() == null) ? 0 : getDepthSearch().hashCode());
        result = prime * result + ((getShallownessSearch() == null) ? 0 : getShallownessSearch().hashCode());
        result = prime * result + ((getFreeSpaceSearch() == null) ? 0 : getFreeSpaceSearch().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_packing_tactics
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        fileId("file_id", "fileId", "INTEGER", false),
        widthPriority("width_priority", "widthPriority", "BIT", false),
        lengthPriority("length_priority", "lengthPriority", "BIT", false),
        quantityPriority("quantity_priority", "quantityPriority", "BIT", false),
        cubePriority("cube_priority", "cubePriority", "BIT", false),
        depthSearch("depth_search", "depthSearch", "BIT", false),
        shallownessSearch("Shallowness_search", "shallownessSearch", "BIT", false),
        freeSpaceSearch("free_space_search", "freeSpaceSearch", "BIT", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_packing_tactics
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}